
# Alacritty Ash Theme

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1c1c1c"
foreground = "#c6c6c6"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "#1c1c1c"
red = "#8a8a8a"
green = "#767676"
yellow = "#9e9e9e"
blue = "#626262"
magenta = "#8a8a8a"
cyan = "#767676"
white = "#c6c6c6"

[colors.bright]
black = "#8a8a8a"
red = "#9e9e9e"
green = "#767676"
yellow = "#b2b2b2"
blue = "#626262"
magenta = "#8a8a8a"
cyan = "#9e9e9e"
white = "#e0e0e0"
